### ISSUE TITLE
glowsoup gives regular bowl when eaten

### ISSUE THREAD

**Issue by scp-3537** [CalaMariGold/TREPIDATION#10] opened 2023-02-25 18:25 UTC

**Comment by CalaMariGold** [comment] 2023-02-25 18:25
also need to fix recipe so it only accepts glowood bowl

**Comment by CalaMariGold** [comment] 2023-03-01 18:03
"glowsoup gives regular bowl when eaten"

I couldn't reproduce this on my end. It gave me a glowood bowl.

**Comment by CalaMariGold** [comment] 2023-03-05 17:40
Fixed in 0.3.1

**Closed as completed by CalaMariGold** 2023-03-05 17:40 UTC
Labels: bug, Fixed next update
