### ISSUE TITLE
[BUG] Various glitches in multiplayer

### ISSUE THREAD

**Issue by CoolJoe2003** [CalaMariGold/TREPIDATION#22] opened 2023-11-06 23:51 UTC
I have been playing multiplayer on my friend's world for a few runs. Some glitches I have found occasionally are:
- My spawn being set to on top of the map.
- After dying and my friend resetting the run before I click respawn, my screen stays red, I can't move, and my tools are glitched until I kill myself with commands.
- Sometimes after killing the wither, his drops spawn every tick, sometimes until the game crashes. If it crashes, then the world is completely unusable and a new one has to be made.
- After running out of time, I died, but I didn't go into spectator mode nor did it say anything in chat. I soon died again and this was fixed.
- While dual wielding, it's often hard to open the crafting table or furnace interface because it keeps swinging the sword instead. This is especially a problem because I kept hitting my friend while trying to do so.
- The riftbreaker crystal breaks block and gives levitation, but it doesn't send us through the portal. When we try to break through, we can mine the first transition portal block but not the second. We eventually run out of levitation and fall to our deaths.
- While floating on the ceiling while using the riftbreaker crystal, placing a block on transition portal block causes me to phase through the roof and keep floating upwards above the map. If I don't die from fall damage, I can mine back down and go though the portal, but that is unlikely.
- After defeating the wither, my friend is invisible to me and I am invisible to my friend. This goes away not too long after after at least 30 (guestimating).
- Dropping items by dragging them out of your inventory sometimes deletes them.
- Me and my friend spawn in completely different areas sometimes.
- Death markers sometimes don't appear, causing all items to vanish. Possibly more so when in an enclosed space.
- Not sure if glitch but dreadswines don't forgive you even after multiple deaths and get angry by being too close.
- Any regular book is called Tome of the Veil.
- Timer times don't sync for multiple people, and using the timer bonus only gives time to one player. One person running out of time causes both players to fail the run, even if the other still had time left.
- Sometimes dying doesn't ever put you in spectator mode and you keep dying in an endless loop. I haven't tried but this would probably make it really hard to click the reset run button since you immediately spawn on enemies.

Here is a compilation of all of these glitches except the last seven in a youtube video I made: https://youtu.be/ELT-x3htydI

**Comment by unnecessarymb** [comment] 2023-11-07 01:22
Regarding point 3: "Sometimes after killing the wither, his drops spawn every tick, sometimes until the game crashes. If it crashes, then the world is completely unusable and a new one has to be made."
Do _all_ drops drop every tick or just the things like the timer bonuses and riftbreaker crystals?

**Comment by CalaMariGold** [comment] 2023-11-10 17:52
I'll go through 1 by 1:

- My spawn being set to on top of the map.
I have no idea what's causing this. Must be multiplayer only bug.

- After dying and my friend resetting the run before I click respawn, my screen stays red, I can't move, and my tools are glitched until I kill myself with commands.
Also no idea.

- Sometimes after killing the wither, his drops spawn every tick, sometimes until the game crashes. If it crashes, then the world is completely unusable and a new one has to be made.
https://github.com/CalaMariGold/TREPIDATION/issues/21

- After running out of time, I died, but I didn't go into spectator mode nor did it say anything in chat. I soon died again and this was fixed.
No idea. Multiplayer bug.

- While dual wielding, it's often hard to open the crafting table or furnace interface because it keeps swinging the sword instead. This is especially a problem because I kept hitting my friend while trying to do so.
Bug with immersive combat. Already reported.

- The riftbreaker crystal breaks block and gives levitation, but it doesn't send us through the portal. When we try to break through, we can mine the first transition portal block but not the second. We eventually run out of levitation and fall to our deaths.
Don't hold left click. Just tap left click for each block. Not exactly a bug, but just bad game design. Not sure how to fix this.

- While floating on the ceiling while using the riftbreaker crystal, placing a block on transition portal block causes me to phase through the roof and keep floating upwards above the map. If I don't die from fall damage, I can mine back down and go though the portal, but that is unlikely.
Don't place a block then.

- After defeating the wither, my friend is invisible to me and I am invisible to my friend. This goes away not too long after after at least 30 (guestimating).
Intentional so mobs don't attack you. I'll add a glowing effect so you can see your friend.

- Dropping items by dragging them out of your inventory sometimes deletes them.
You have cheats on and are dragging the item into the JEI interface. Drag items towards the top or bottom of the inventory.

- Me and my friend spawn in completely different areas sometimes.
https://github.com/CalaMariGold/TREPIDATION/issues/19

- Death markers sometimes don't appear, causing all items to vanish. Possibly more so when in an enclosed space.
No idea. Multiplayer bug.

- Not sure if glitch but dreadswines don't forgive you even after multiple deaths and get angry by being too close.
Not a bug. Don't touch them.

- Any regular book is called Tome of the Veil.
Known issue. Not a big deal since you aren't crafting books anyway.

- Timer times don't sync for multiple people, and using the timer bonus only gives time to one player. One person running out of time causes both players to fail the run, even if the other still had time left.
Time is separate per player. There isn't really a way to make it globally, but maybe in the future. This isn't really a bug but again, bad game design. 

- Sometimes dying doesn't ever put you in spectator mode and you keep dying in an endless loop. I haven't tried but this would probably make it really hard to click the reset run button since you immediately spawn on enemies.
No idea. Multiplayer bug.


I'm going to close this issue, please make separate reports for each issue (aside from the ones i said aren't a bug). If not I'll make the issues myself eventually

**Closed as completed by CalaMariGold** 2023-11-10 17:52 UTC
Labels: bug
